DISCARD ALL;	
EXPLAIN (ANALYZE) SELECT "is"		FROM table2 WHERE "is" 	=  500;
\r
DISCARD ALL;
EXPLAIN (ANALYZE) SELECT "is"		FROM table2 WHERE "is" 	=  500;
\r
DISCARD ALL;
EXPLAIN (ANALYZE) SELECT "is"		FROM table2 WHERE "is" 	=  500;
\r
DISCARD ALL;
EXPLAIN (ANALYZE) SELECT "is"		FROM table2 WHERE "is" 	=  500;
\r
DISCARD ALL;
EXPLAIN (ANALYZE) SELECT "is"		FROM table2 WHERE "is" 	=  500;
\r
DISCARD ALL;
EXPLAIN (ANALYZE) SELECT "is"		FROM table2 WHERE "is" 	=  500;
\r
DISCARD ALL;
EXPLAIN (ANALYZE) SELECT "is"		FROM table2 WHERE "is" 	=  500;
\r
DISCARD ALL;
EXPLAIN (ANALYZE) SELECT "is"		FROM table2 WHERE "is" 	=  500;
\r
DISCARD ALL;
EXPLAIN (ANALYZE) SELECT "is"		FROM table2 WHERE "is" 	=  500;
\r
DISCARD ALL;
EXPLAIN (ANALYZE) SELECT "is"		FROM table2 WHERE "is" 	=  500;
\r