-- MySQL Script generated by MySQL Workbench
-- 12/07/16 22:24:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema progweb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `progweb` ;

-- -----------------------------------------------------
-- Schema progweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `progweb` DEFAULT CHARACTER SET utf8 ;
USE `progweb` ;

-- -----------------------------------------------------
-- Table `progweb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progweb`.`user` ;

CREATE TABLE IF NOT EXISTS `progweb`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(45) ,
  `identity_number` VARCHAR(255) ,
  `created_at` DATETIME  DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME  DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `progweb`.`professional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progweb`.`professional` ;

CREATE TABLE IF NOT EXISTS `progweb`.`professional` (
  `id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_professional_user`
    FOREIGN KEY (`id`)
    REFERENCES `progweb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progweb`.`service_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progweb`.`service_category` ;

CREATE TABLE IF NOT EXISTS `progweb`.`service_category` (
  `created_at` DATETIME  DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME  DEFAULT CURRENT_TIMESTAMP,
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `parent_id` INT UNSIGNED ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_service_category_service_category1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_service_category_service_category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `progweb`.`service_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `progweb`.`professional_has_service_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progweb`.`professional_has_service_category` ;

CREATE TABLE IF NOT EXISTS `progweb`.`professional_has_service_category` (
  `professional_id` INT UNSIGNED NOT NULL,
  `service_category_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME  DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME  DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`professional_id`, `service_category_id`),
  INDEX `fk_professional_has_service_category_service_category1_idx` (`service_category_id` ASC),
  INDEX `fk_professional_has_service_category_professional1_idx` (`professional_id` ASC),
  CONSTRAINT `fk_professional_has_service_category_professional1`
    FOREIGN KEY (`professional_id`)
    REFERENCES `progweb`.`professional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professional_has_service_category_service_category1`
    FOREIGN KEY (`service_category_id`)
    REFERENCES `progweb`.`service_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progweb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progweb`.`client` ;

CREATE TABLE IF NOT EXISTS `progweb`.`client` (
  `id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_user1_idx` (`id` ASC),
  CONSTRAINT `fk_client_user1`
    FOREIGN KEY (`id`)
    REFERENCES `progweb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progweb`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progweb`.`country` ;

CREATE TABLE IF NOT EXISTS `progweb`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(2) NOT NULL,
  `code3` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progweb`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progweb`.`state` ;

CREATE TABLE IF NOT EXISTS `progweb`.`state` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `short_name` VARCHAR(3) ,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_state_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_state_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `progweb`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progweb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progweb`.`city` ;

CREATE TABLE IF NOT EXISTS `progweb`.`city` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `state_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_state1_idx` (`state_id` ASC),
  CONSTRAINT `fk_city_state1`
    FOREIGN KEY (`state_id`)
    REFERENCES `progweb`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progweb`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progweb`.`address` ;

CREATE TABLE IF NOT EXISTS `progweb`.`address` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city_id` INT UNSIGNED NOT NULL,
  `postal_code` VARCHAR(150) NOT NULL,
  `complement` VARCHAR(200) ,
  `district` VARCHAR(100) NOT NULL,
  `number` VARCHAR(50) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `created_at` DATETIME  DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME  DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_address_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `progweb`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progweb`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progweb`.`service` ;

CREATE TABLE IF NOT EXISTS `progweb`.`service` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_category_id` INT UNSIGNED NOT NULL,
  `address_id` INT UNSIGNED NOT NULL,
  `client_id` INT UNSIGNED NOT NULL,
  `price` DECIMAL(20,2) ,
  `professional_id` INT UNSIGNED NOT NULL,
  `observation` VARCHAR(255) ,
  `paid` TINYINT(1) ,
  `status` TINYINT UNSIGNED ,
  `created_at` DATETIME  DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME  DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_service_service_category1_idx` (`service_category_id` ASC),
  INDEX `fk_service_address1_idx` (`address_id` ASC),
  INDEX `fk_service_professional1_idx` (`professional_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_service_service_category1`
    FOREIGN KEY (`service_category_id`)
    REFERENCES `progweb`.`service_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `progweb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_professional1`
    FOREIGN KEY (`professional_id`)
    REFERENCES `progweb`.`professional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
